public with sharing class PokemonWrapper {
    

        public class PokemonDetailWrapper {
            public SpritesWrapper sprites;
        }

        public class SpritesWrapper {
            public string front_default;
        }

        public class OtherWrapper {
            public DreamWorldWrapper;
        }

        public class DreamWorldWrapper {
            public string front_default;
        }

        public class StatsWrapper {
            public integer base_stat;
        }

        public class StatWrapper {
            public string name;
        }

}
